### ISSUE TITLE
Site Down

### ISSUE THREAD

**Issue by rochiey** [OMGToFo/SPSStoExcel#2]
![image](https://github.com/OMGToFo/SPSStoExcel/assets/38701913/064c21dd-7f8f-4766-a4d2-490e29ceb016)

**Comment by OMGToFo** [comment]
Thanx for the info, I restarted the app. it crashes now and then for sure when much data is loaded, I'm using free service fron streamlit.

**Comment by rochiey** [comment]
My bad I might have crashed it but I only used 1.3mb file but the columns are up to 1000+. Thanks for the service even though its free, it's a useful tool for an online sav reader.

**Comment by OMGToFo** [comment]
no, 1.3 mb shouldn't crash it, unless there were many more using the app at the same time, which I strongly doubt. I think the simple export to excel function should work well.  then I tried some further stuff with charting and cross tabulations that might not be so reliable. I mainly use the export to excel with and without labels, as I do not have access to a spss license any more
